# Generated by Django 5.2.1 on 2025-06-12 16:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='konto',
            fields=[
                ('konto_id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=255, unique=True)),
                ('haslo', models.CharField(max_length=255)),
                ('rola', models.CharField(choices=[('student', 'student'), ('nauczyciel', 'nauczyciel'), ('admin', 'admin')], max_length=20)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='semestr',
            fields=[
                ('semestr_id', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(choices=[('letni', 'letni'), ('zimowy', 'zimowy')], max_length=10)),
                ('data_rozpoczecia', models.DateField()),
                ('data_zakonczenia', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='nauczyciel',
            fields=[
                ('nauczyciel_id', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=255)),
                ('nazwisko', models.CharField(max_length=255)),
                ('tytul', models.CharField(max_length=255)),
                ('konto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.konto')),
            ],
        ),
        migrations.CreateModel(
            name='ocena',
            fields=[
                ('ocena_id', models.AutoField(primary_key=True, serialize=False)),
                ('wartosc', models.DecimalField(decimal_places=2, max_digits=4)),
                ('data_wprowadzenia', models.DateTimeField()),
                ('nauczyciel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.nauczyciel')),
            ],
        ),
        migrations.CreateModel(
            name='historia_ocen',
            fields=[
                ('historia_id', models.AutoField(primary_key=True, serialize=False)),
                ('wartosc', models.DecimalField(decimal_places=2, max_digits=4)),
                ('data_zmiany', models.DateTimeField()),
                ('nauczyciel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.nauczyciel')),
                ('ocena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ocena')),
            ],
        ),
        migrations.CreateModel(
            name='przedmiot',
            fields=[
                ('przedmiot_id', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=255)),
                ('kierunek', models.CharField(max_length=255)),
                ('rok_studiow', models.IntegerField()),
                ('nauczyciel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.nauczyciel')),
            ],
        ),
        migrations.AddField(
            model_name='ocena',
            name='przedmiot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.przedmiot'),
        ),
        migrations.CreateModel(
            name='grupa_zajeciowa',
            fields=[
                ('grupa_id', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=255)),
                ('przedmiot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.przedmiot')),
            ],
        ),
        migrations.AddField(
            model_name='ocena',
            name='semestr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.semestr'),
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=255)),
                ('nazwisko', models.CharField(max_length=255)),
                ('kierunek', models.CharField(max_length=255)),
                ('rok_studiow', models.IntegerField()),
                ('konto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.konto')),
            ],
        ),
        migrations.AddField(
            model_name='ocena',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.student'),
        ),
        migrations.CreateModel(
            name='zaliczenie',
            fields=[
                ('zaliczenie_id', models.AutoField(primary_key=True, serialize=False)),
                ('typ', models.CharField(choices=[('egzamin', 'egzamin'), ('kolokwium', 'kolokwium'), ('projekt', 'projekt')], max_length=20)),
                ('data', models.DateTimeField()),
                ('przedmiot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.przedmiot')),
            ],
        ),
        migrations.CreateModel(
            name='student_grupa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.grupa_zajeciowa')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.student')),
            ],
            options={
                'unique_together': {('student', 'grupa')},
            },
        ),
    ]
