# Generated by Django 5.2.1 on 2025-06-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_grupa',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
