# Generated by Django 5.2.1 on 2025-06-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_student_grupa_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_grupa',
            name='age',
        ),
        migrations.RemoveField(
            model_name='student_grupa',
            name='name',
        ),
        migrations.AddIndex(
            model_name='historia_ocen',
            index=models.Index(fields=['ocena'], name='mainapp_his_ocena_i_5212c0_idx'),
        ),
        migrations.AddIndex(
            model_name='ocena',
            index=models.Index(fields=['student'], name='mainapp_oce_student_0401aa_idx'),
        ),
        migrations.AddIndex(
            model_name='ocena',
            index=models.Index(fields=['przedmiot'], name='mainapp_oce_przedmi_03c342_idx'),
        ),
        migrations.AddIndex(
            model_name='student_grupa',
            index=models.Index(fields=['student'], name='mainapp_stu_student_3ac6eb_idx'),
        ),
        migrations.AddIndex(
            model_name='student_grupa',
            index=models.Index(fields=['grupa'], name='mainapp_stu_grupa_i_04aa3a_idx'),
        ),
    ]
